name: Unit tests

on:
  push:
    branches:
      - 'master'
    tags:
      - '*'
  pull_request:

jobs:
  build:
    strategy:
      matrix:
        php: ['7.2', '7.3', '7.4']
    runs-on: ubuntu-latest
    name: PHP ${{ matrix.php }}
    
    steps:
    - uses: actions/checkout@v1
      
    - name: Setup PHP
      uses: shivammathur/setup-php@v1
      with:
        php-version: ${{ matrix.php }}
        extensions: mbstring, intl, json
        coverage: pcov
        tools: composer:v2

    - name: Validate composer.json and composer.lock
      run: composer validate

    - name: Run PHP lint
      run: find . -name \*.php ! -path "./public/*" ! -path "./vendor/*" | xargs -n1 php -d display_errors=stderr -l
