name: Release

on:
  push:
    tags:
      - '*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      
    - name: Setup PHP
      uses: shivammathur/setup-php@v1
      with:
        php-version: "7.4"
        extensions: mbstring, intl, json
        coverage: pcov
        tools: composer:v2

    - name: Build extension ZIP
      run: |
        composer extension-package

    - name: Release ZIP on Github
      uses: softprops/action-gh-release@v1
      with:
        files: |
          varnishcache_*.zip
      env:
        GITHUB_TOKEN: ${{ secrets.RELEASE_USER_TOKEN }}
    
    - name: Prepare TER release
      run: |
        mkdir ter-upload
        unzip -d ter-upload ./varnishcache_*.zip
    
    - name: Release ZIP on TER
      uses: mittwald/typo3-publish-ter-action@v1.0.0-beta1
      with:
        ter-username: ${{ secrets.TER_USERNAME }}
        ter-password: ${{ secrets.TER_PASSWORD }}
        extension-key: varnishcache
        extension-dir: ./ter-upload